name: Publish to Cloudflare Pages
on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'Cloudflare'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Download Nuxt Artifacts
        uses: actions/download-artifact@v4
        with:
          path: nuxt-build-output
      - name: Build Resume
        run: pnpm run generate
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: resume
          directory: dist